package com.closs.types.product

data class Product(
    val codigo: String = "",
    val comprometido: Double = 0.0,
    val dctotope: Double = 0.0,
    val discont: Double = 0.0,
    val enpreventa: String = "",
    val existencia: Double = 0.0,
    val fechamodifi: String = "",
    val grupo: String = "",
    val marca: String = "",
    val nombre: String = "",
    val precio1: Double = 0.0,
    val precio2: Double = 0.0,
    val precio3: Double = 0.0,
    val precio4: Double = 0.0,
    val precio5: Double = 0.0,
    val precio6: Double = 0.0,
    val precio7: Double = 0.0,
    val referencia: String = "",
    val subgrupo: String = "",
    val unidad: String = "",
    val vtaMax: Double = 0.0,
    val vtaMin: Double = 0.0,
    val vtaMinenx: Double = 0.0,
    val vtaSolofac: Int = 0,
    val vtaSolone: Int = 0,
    val costoProm: Double = 0.0,
    val util1: Double = 0.0,
    val util2: Double = 0.0,
    val util3: Double = 0.0,
    val fchUltComp: String = "",
    val qtyUltComp: Double = 0.0,
    val url: String = "",
    val userId: String = "",
)
